### ISSUE TITLE
Australian Events

### ISSUE THREAD

**Issue by HybridAU** [hannob/hackercon#2]
I was going to send a pull request for
 * [Ruxcon](https://ruxcon.org.au/) - Melbourne, Australia
 * [Kiwicon](https://www.kiwicon.org/) - New Zealand

But neither of these events seem to have published their dates for upcoming events; Ruxcon be a weekend in mid October (possibly the 21st and 22nd), Kiwicon will probably be late November I could put in tentative dates, but I think it's better to wait until they are announced.

**Comment by hannob** [comment]
I've added a list for confs with unannounced date
